openapi: 3.2.0
info:
  title: stream-api Meta.json?top Count API
  version: '1.1'
servers:
- url: https://api.massrelevance.com
security:
- sec0: []
tags:
- name: Meta.json?top Count
paths:
  /{account}/{streamName}/meta.json?top_count:
    get:
      summary: Get tweets per period
      description: Number of tweets to include per period
      operationId: get-top-retweets-hourly-from-now
      parameters:
      - name: account
        in: path
        schema:
          type: string
        required: true
      - name: streamName
        in: path
        schema:
          type: string
        required: true
      - name: top_count
        in: query
        schema:
          type: integer
          format: int32
          default: 5
      responses:
        '200':
          description: '200'
          content:
            text/plain:
              examples:
                Result:
                  value: Coming Soon
      deprecated: false
      security: []
      tags:
      - Meta.json?top Count
components:
  securitySchemes:
    sec0:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://example.com/oauth2/token
          scopes: {}
x-readme:
  headers: []
  explorer-enabled: false
  proxy-enabled: true
x-readme-fauxas: true
