openapi: 3.2.0
info:
  title: stream-api Meta.json?precision API
  version: '1.1'
servers:
- url: https://api.massrelevance.com
security:
- sec0: []
tags:
- name: Meta.json?precision
paths:
  /{account}/{streamName}/meta.json?precision:
    get:
      summary: Get specific decimals in percent return
      description: Determines the number of decimal places to return in percentages
      operationId: get-specific-decimals-in-percent-return
      parameters:
      - name: account
        in: path
        schema:
          type: string
        required: true
      - name: streamName
        in: path
        schema:
          type: string
        required: true
      - name: precision
        in: query
        schema:
          type: integer
          format: int32
          default: 1
      responses:
        '200':
          description: '200'
          content:
            text/plain:
              examples:
                Result:
                  value: Coming Soon
      deprecated: false
      security: []
      tags:
      - Meta.json?precision
components:
  securitySchemes:
    sec0:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://example.com/oauth2/token
          scopes: {}
x-readme:
  headers: []
  explorer-enabled: false
  proxy-enabled: true
x-readme-fauxas: true
